post_upgrade() {
    if /usr/bin/pacman-key --list-keys >/dev/null 2>&1; then
        /usr/bin/pacman-key --populate archimedeos
    else
        echo ">>> Run 'pacman-key --init' to set up your pacman keyring."
        echo ">>> Then run 'pacman-key --populate archimedeos' to install the ArchimedeOS keyring."
    fi
}

post_install() {
    if [ -x /usr/bin/pacman-key ]; then
        post_upgrade
    fi
}
